# Default values for cassandra.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

## Redis image version
image: gcr.io/google_containers/redis:v1
imagePullPolicy: IfNotPresent

## Replica count
slaveReplicaCount: 3
sentinelReplicaCount: 2

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    memory: 500Mi

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  storageClass: default
  accessMode: ReadWriteOnce
  size: 1Gi