name: elk
home: http://www.fluentd.org/
version: 0.1.3
description: Log Aggregation with Fluentd, Elasticsearch and Kibana.
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
maintainers:
  - name: Erik Schlegel
    email: erik.schlegel@gmail.com
