# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: master
  Image: "timfpark/spark"
  ImageTag: "2.1"
  Replicas: 1
  Component: "spark-master"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 7077
  ContainerPort: 7077
  # Set Master JVM memory. Default 1g
  #DaemonMemory: 1g

WebUi:
  Name: webui
  ServicePort: 8080
  Component: "spark-webui"
  ProxyPort: 80
  ContainerPort: 8080
  Image: "elsonrodriguez/spark-ui-proxy:1.0"

Worker:
  Name: worker
  Image: "timfpark/spark"
  ImageTag: "2.1"
  ImagePullPolicy: "Always"
  Replicas: 3
  Component: "spark-worker"
  WorkingDirectory: "/opt/spark/work"
  Cpu: "100m"
  Memory: "512Mi"
  ContainerPort: 8081
  Environment:
  - name: SPARK_DAEMON_MEMORY
    value: 1g
  - name: SPARK_WORKER_MEMORY
    value: 1g

Zeppelin:
  Name: zeppelin
  Image: "gcr.io/google_containers/zeppelin"
  ImageTag: "v0.5.5_v2"
  Replicas: 1
  Component: "zeppelin"
  Cpu: "100m"
  ServicePort: 8080
  ContainerPort: 8080

Persistence:
  Enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <StorageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # StorageClass:
  AccessMode: ReadWriteOnce
  StorageClass: fast
  Size: 8Gi
  Sku: Premium_LRS
  Provisioner: kubernetes.io/azure-disk
  Location: eastus
  Volumes:
#  - name: nothing
#    emptyDir: {}
  Mounts:
#  - mountPath: /var/nothing
#    name: nothing
#    readOnly: true