apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-sentinel
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: sentinel
        image: {{ .Values.redis_image }}
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
spec:
  serviceName: "redis"
  replicas: 3
  template:
    metadata:
      labels:
        name: redis
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis_image }}
        ports:
        - containerPort: 6379
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
      {{- if eq .Values.persistence.enabled false }}
      - name: data
        emptyDir: {}
      {{- end}}
  volumeClaimTemplates:
  {{- if .Values.persistence.enabled }}
  - metadata:
      name: data
      annotations:
        {{- if .Values.persistence.storageClass }}
        volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass }}
        {{- else }}
        volume.alpha.kubernetes.io/storage-class: default
        {{- end }}
    spec:
      accessModes:
      - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
  {{- end }}