apiVersion: v1
kind: Service
metadata:
  name: {{.Values.Kibana.name}}
  labels:
    app: {{.Values.Kibana.app}}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kibana"
spec:
  type: LoadBalancer
  selector:
    component: {{.Values.Kibana.component}}
  ports:
    - name: http
      port: {{.Values.Kibana.port}}
      protocol: TCP
  loadBalancerSourceRanges:
    {{range .Values.Kibana.lb_source}}
    - {{.}}
    {{end}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.Kibana.name}}
spec:
  replicas: {{.Values.Kibana.replicas}}
  template:
    metadata:
      labels:
        component: {{.Values.Kibana.component}}
    spec:
      containers:
      - name: {{.Values.Kibana.container_name}}
        image: {{.Values.Kibana.image}}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: {{.Values.Kibana.cpu_limit}}
          requests:
            cpu: {{.Values.Kibana.cpu_requests}}
        env:
          - name: "ELASTICSEARCH_URL"
            value: "{{.Values.Kibana.elastic_host}}"
        {{range .Values.Kibana.env_vars}}
          - name: {{.name}}
            value: "{{.value}}"
        {{end}}
        ports:
        - containerPort: {{.Values.Kibana.container_port}}
          name: ui
          protocol: TCP