apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: {{ template "master-fullname" . }}
 labels:
   heritage: {{.Release.Service | quote }}
   release: {{.Release.Name | quote }}
   chart: "{{.Chart.Name}}-{{.Chart.Version}}"
   component: "{{.Release.Name}}-{{.Values.Master.Component}}"
spec:
  rules:
    - host: k8s.spark.com
      http:
        paths:
          - path: /ui
            backend:
              serviceName: {{ template "master-fullname" . }}
              servicePort: {{.Values.WebUi.ContainerPort}}
          - path: /static
            backend:
              serviceName: {{ template "master-fullname" . }}
              servicePort: {{.Values.WebUi.ContainerPort}}