apiVersion: v1
kind: Secret
metadata:
  name: checkpointing-pvc-secret
type: Opaque
data:
 {{ if .Values.Persistence.PvcAcctName }}
  azurestorageaccountname: {{ .Values.Persistence.PvcAcctName | b64enc | quote }}
 {{ else }}
  azurestorageaccountname: {{ randAlphaNum 10 | b64enc | quote }}
 {{ end }}
 {{ if .Values.Persistence.PvcPwd }}
  azurestorageaccountkey: {{ .Values.Persistence.PvcPwd | b64enc | quote }}
 {{ else }}
  azurestorageaccountkey: {{ randAlphaNum 10 | b64enc | quote }}
 {{ end }}