apiVersion: v1
kind: Service
metadata:
  name: zeppelin
spec:
  ports:
    - port: {{.Values.Zeppelin.ServicePort}}
      targetPort: {{.Values.Zeppelin.ContainerPort}}
  selector:
    component: zeppelin
  type: "LoadBalancer"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zeppelin-controller
spec:
  replicas: {{default 1 .Values.Zeppelin.Replicas}}
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: "{{.Values.Zeppelin.Image}}:{{.Values.Zeppelin.ImageTag}}"
          ports:
            - containerPort: {{.Values.Zeppelin.ContainerPort}}
          resources:
            requests:
              cpu: "{{.Values.Zeppelin.Cpu}}"
