apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-master
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: {{.Values.Master.Component}}
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: {{.Values.Master.Component}}
    spec:
      containers:
        - name: {{.Values.Master.Component}}
          imagePullPolicy: "{{.Values.Master.ImagePullPolicy}}"
          image: "{{.Values.Master.Image}}:{{.Values.Master.ImageTag}}"
          {{- if .Values.Master.SparkSubmitCommand }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    {{.Values.Master.SparkSubmitCommand}}
          {{- end }}
          ports:
            - containerPort: {{.Values.Master.ContainerPort}}
            - containerPort: {{.Values.WebUi.ContainerPort}}
          resources:
            requests:
              cpu: "{{.Values.Master.Resources.Requests.Cpu}}"
              memory: "{{.Values.Master.Resources.Requests.Memory}}"
            limits:
              cpu: "{{.Values.Master.Resources.Limits.Cpu}}"
              memory: "{{.Values.Master.Resources.Limits.Memory}}"
          {{- if .Values.Master.ConfigMapName }}
          envFrom:
          - configMapRef:
              name: "{{.Values.Master.ConfigMapName}}"
          {{ else }}
          env:
          - name: SPARK_DAEMON_MEMORY
            value: {{ default "1g" .Values.Master.DaemonMemory | quote }}
          {{- if .Values.Master.EnableHA }}
          - name: SPARK_DAEMON_JAVA_OPTS
            value: "-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=zookeeper.spark.svc.cluster.local:2181"
          {{- end }}
          {{- end }}